services:
  javaapp:
    build: ./SistemaGerenciadorDeVeiculo/
    command: ./executar.sh
    depends_on:
      - postgresql

  postgresql:
    build: ./postgresql/
    restart: always
    environment:
      POSTGRES_DATABASE: 'db'
      POSTGRES_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'