services:
  javaapp:
    build: ./SistemaGerenciadorDeVeiculo/
    depends_on:
      - db
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=123456
    stdin_open: true
    tty: true 
    ports:
      - 8080:8080
    entrypoint: ["/app/wait-for-it.sh", "db:5432", "--", "java", "-jar", "/app/SistemaGerenciadorDeVeiculo-0.0.1-SNAPSHOT.jar"]

  db:
    build:
      context: ./SistemaGerenciadorDeVeiculo/db # Ajuste para o caminho correto do Dockerfile do banco de dados
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '123456'
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  db-data:
