services:
  javaapp:
    build: ./java-app/
    depends_on:
      - db

  db:
    build: ./db/
    restart: always
    environment:
      POSTGRES_DATABASE: 'db'
      POSTGRES_USERNAME: 'postgres'
      POSTGRES_PASSWORD: '12345'
    ports:
      - '3306:3306'