services:
  javaapp:
    build: ./SistemaGerenciadorDeVeiculo/
    depends_on:
      - db
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=123456
    ports:
      - "8080:8080"
    entrypoint: ["/app/wait-for-it.sh", "db:5432", "--", "java", "-jar", "/app/SistemaGerenciadorDeVeiculo-0.0.1-SNAPSHOT.jar"]

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '123456'
    ports:
      - '5433:5432'
