FROM openjdk:17

ADD target/SistemaGerenciadorDeVeiculo-0.0.1-SNAPSHOT.jar app/SistemaGerenciadorDeVeiculo-0.0.1-SNAPSHOT.jar

ENTRYPOINT [ "java", "-jar", "app/SistemaGerenciadorDeVeiculo-0.0.1-SNAPSHOT.jar" ]